as_danger_classes_original = ['Accelerating, revving, vroom',
                           'Air brake',
                           'Air conditioning',
                           'Air horn, truck horn',
                           'Aircraft',
                           'Aircraft engine',
                           'Alarm',
                           'Alarm clock',
                           'Alert',
                           'Ambulance (siren)',
                           'Animal',
                           'Applause',
                           'Arrow',
                           'Artillery fire',
                           'Audio logo',
                           'Babbling',
                           'Baby cry, infant cry',
                           'Baby laughter',
                           'Background noise',
                           'Bang',
                           'Bark',
                           'Basketball bounce',
                           'Bathroom sounds',
                           'Bathtub (filling or washing)',
                           'Battle cry',
                           'Bee, wasp, etc.',
                           'Beep, bleep',
                           'Bell',
                           'Bellow',
                           'Belly laugh',
                           'Bicycle bell',
                           'Bicycle, tricycle',
                           'Bird',
                           'Bird flight, flapping wings',
                           'Bird vocalization, bird call, bird song',
                           'Biting',
                           'Bleat',
                           'Blender, food processor',
                           'Boat, Water vehicle',
                           'Boiling',
                           'Boing',
                           'Booing',
                           'Boom',
                           'Bouncing',
                           'Bow-wow',
                           'Breaking',
                           'Breathing',
                           'Brief tone',
                           'Burping, eructation',
                           'Burst, pop',
                           'Bus',
                           'Busy signal',
                           'Buzz',
                           'Buzzer',
                           'Cacophony',
                           'Camera',
                           'Canidae, wild dogs, wolves',
                           'Cap gun',
                           'Car',
                           'Car alarm',
                           'Car passing by',
                           'Carbon monoxide detector, CO detector',
                           'Cart',
                           'Cash register',
                           'Cat',
                           'Caterwaul',
                           'Cattle, bovinae',
                           'Caw',
                           'Cellphone buzz, vibrating alert',
                           'Chain',
                           'Chainsaw',
                           'Change ringing (campanology)',
                           'Channel, environment and background',
                           'Chant',
                           'Cheering',
                           'Chewing, mastication',
                           'Chicken, rooster',
                           'Child singing',
                           'Child speech, kid speaking',
                           'Children playing',
                           'Children shouting',
                           'Chime',
                           'Chipmunk',
                           'Chirp tone',
                           'Chirp, tweet',
                           'Choir',
                           'Chop',
                           'Chopping (food)',
                           'Chorus effect',
                           'Chuckle, chortle',
                           'Church bell',
                           'Civil defense siren',
                           'Clang',
                           'Clapping',
                           'Clatter',
                           'Clickety-clack',
                           'Clicking',
                           'Clip-clop',
                           'Clock',
                           'Cluck',
                           'Clunk',
                           'Coin (dropping)',
                           'Computer keyboard',
                           'Conversation',
                           'Coo',
                           'Cough',
                           'Cowbell',
                           'Crack',
                           'Crackle',
                           'Creak',
                           'Cricket',
                           'Croak',
                           'Crockery breaking and smashing',
                           'Crow',
                           'Crowd',
                           'Crowing, cock-a-doodle-doo',
                           'Crumpling, crinkling',
                           'Crunch',
                           'Crushing',
                           'Crying, sobbing',
                           'Cupboard open or close',
                           'Cutlery, silverware',
                           'Deformable shell',
                           "Dental drill, dentist's drill",
                           'Dial tone',
                           'Digestive',
                           'Ding',
                           'Ding-dong',
                           'Dishes, pots, and pans',
                           'Distortion',
                           'Dog',
                           'Domestic animals, pets',
                           'Dong, bong',
                           'Donkey, ass',
                           'Door',
                           'Doorbell',
                           'Drawer open or close',
                           'Drill',
                           'Drip',
                           'Duck call (hunting tool)',
                           'Ducks, geese, waterfowl',
                           'Echo',
                           'Effects unit',
                           'Electric rotor drone, quadcopter',
                           'Electric shaver, electric razor',
                           'Electric toothbrush',
                           'Electronic tuner',
                           'Emergency vehicle',
                           'Engine',
                           'Engine knocking',
                           'Engine starting',
                           'Environmental noise',
                           'Error signal',
                           'Eruption',
                           'Explosion',
                           'Fart',
                           'Female singing',
                           'Female speech, woman speaking',
                           'Filing (rasp)',
                           'Fill (with liquid)',
                           'Finger snapping',
                           'Fire',
                           'Fire alarm',
                           'Fire engine, fire truck (siren)',
                           'Firecracker',
                           'Fireworks',
                           'Fixed-wing aircraft, airplane',
                           'Fizz',
                           'Flap',
                           'Fly, housefly',
                           'Foghorn',
                           'Fowl',
                           'Frog',
                           'Frying (food)',
                           'Fusillade',
                           'Gargling',
                           'Gasp',
                           'Gears',
                           'Generic impact sounds',
                           'Giggle',
                           'Glass',
                           'Glass chink, clink',
                           'Glass shatter',
                           'Goat',
                           'Gobble',
                           'Grind',
                           'Groan',
                           'Growling',
                           'Grunt',
                           'Gull, seagull',
                           'Gunshot, gunfire',
                           'Gurgling, bubbling',
                           'Gush',
                           'Hair dryer',
                           'Hammer',
                           'Hands',
                           'Heart sounds, heartbeat',
                           'Heavy engine (low frequency)',
                           'Helicopter',
                           'Hiccup',
                           'Hiss',
                           'Honk',
                           'Hoot',
                           'Horse',
                           'Howl',
                           'Howl (wind)',
                           'Hubbub, speech noise, speech babble',
                           'Hum',
                           'Human group actions',
                           'Human locomotion',
                           'Human sounds',
                           'Human voice',
                           'Humming',
                           'Ice cream truck, ice cream van',
                           'Idling',
                           'Insect',
                           'Inside, large room or hall',
                           'Inside, public space',
                           'Inside, small room',
                           'Jackhammer',
                           'Jet engine',
                           'Jingle bell',
                           'Jingle, tinkle',
                           'Kettle whistle',
                           'Keypress tone',
                           'Keys jangling',
                           'Kitchen and dining room sounds',
                           'Knife',
                           'Knock',
                           'Laughter',
                           'Lawn mower',
                           'Light engine (high frequency)',
                           'Liquid',
                           'Livestock, farm animals, working animals',
                           'Lock',
                           'Machine gun',
                           'Mains hum',
                           'Male singing',
                           'Male speech, man speaking',
                           'Mantra',
                           'Mechanical bell',
                           'Mechanical fan',
                           'Mechanisms',
                           'Medium engine (mid frequency)',
                           'Meow',
                           'Microphone',
                           'Microwave oven',
                           'Moo',
                           'Mosquito',
                           'Motor vehicle (road)',
                           'Motorboat, speedboat',
                           'Motorcycle',
                           'Mouse',
                           'Music',
                           'Narration, monologue',
                           'Neigh, whinny',
                           'Noise',
                           'Non-motorized land vehicle',
                           'Ocean',
                           'Oink',
                           'Other sourceless',
                           'Outside, urban or manmade',
                           'Owl',
                           'Packing tape, duct tape',
                           'Pant',
                           'Pant (dog)',
                           'Paper rustling',
                           'Patter',
                           'Pig',
                           'Pigeon, dove',
                           'Ping',
                           'Plop',
                           'Police car (siren)',
                           'Pour',
                           'Power saw, circular saw, table saw',
                           'Power tool',
                           'Power windows, electric windows',
                           'Printer',
                           'Propeller, airscrew',
                           'Puff',
                           'Pulleys',
                           'Pulse',
                           'Pump (liquid)',
                           'Purr',
                           'Quack',
                           'Race car, auto racing',
                           'Radio',
                           'Rail transport',
                           'Railroad car, train wagon',
                           'Rain',
                           'Rain on surface',
                           'Raindrop',
                           'Rapping',
                           'Ratchet, pawl',
                           'Rattle',
                           'Refrigerator',
                           'Respiratory sounds',
                           'Reverberation',
                           'Reversing beeps',
                           'Ringing tone, ringback tone',
                           'Ringtone',
                           'Roar',
                           'Roaring cats (lions, tigers)',
                           'Rodents, rats, mice',
                           'Roll',
                           'Rowboat, canoe, kayak',
                           'Rub',
                           'Rumble',
                           'Run',
                           'Rustle',
                           'Sailboat, sailing ship',
                           'Sanding',
                           'Sawing',
                           'Scissors',
                           'Scrape',
                           'Scratch',
                           'Screaming',
                           'Screech',
                           'Sewing machine',
                           'Sheep',
                           'Ship',
                           'Shout',
                           'Shower',
                           'Shuffle',
                           'Shuffling cards',
                           'Sigh',
                           'Sine wave',
                           'Singing',
                           'Single-lens reflex camera',
                           'Sink (filling or washing)',
                           'Siren',
                           'Sizzle',
                           'Skateboard',
                           'Slam',
                           'Slap, smack',
                           'Sliding door',
                           'Slosh',
                           'Slurp, drinking straw',
                           'Smash, crash',
                           'Smoke detector, smoke alarm',
                           'Snake',
                           'Snap',
                           'Sneeze',
                           'Snicker',
                           'Sniff',
                           'Snoring',
                           'Snort',
                           'Snort (horse)',
                           'Sonar',
                           'Sonic boom',
                           'Sound effect',
                           'Sound equipment',
                           'Sound reproduction',
                           'Speech',
                           'Speech synthesizer',
                           'Splash, splatter',
                           'Splinter',
                           'Spray',
                           'Squawk',
                           'Squeak',
                           'Squeal',
                           'Squish',
                           'Stairs',
                           'Static',
                           'Steam',
                           'Steam whistle',
                           'Stir',
                           'Stomach rumble',
                           'Stomp, stamp',
                           'Stream, river',
                           'Subway, metro, underground',
                           'Surface contact',
                           'Sweeping',
                           'Synthetic singing',
                           'Tap',
                           'Tap dance',
                           'Tape hiss',
                           'Tearing',
                           'Telephone',
                           'Telephone bell ringing',
                           'Telephone dialing, DTMF',
                           'Television',
                           'Throat clearing',
                           'Thump, thud',
                           'Thunder',
                           'Thunderstorm',
                           'Thunk',
                           'Tick',
                           'Tick-tock',
                           'Tire squeal, skidding',
                           'Toilet flush',
                           'Tools',
                           'Toothbrush',
                           'Traffic noise, roadway noise',
                           'Train',
                           'Train horn',
                           'Train wheels squealing',
                           'Train whistle',
                           'Trickle, dribble',
                           'Truck',
                           'Tuning fork',
                           'Turkey',
                           'Typewriter',
                           'Typing',
                           'Unknown sound',
                           'Vacuum cleaner',
                           'Vehicle',
                           'Vehicle horn, car horn, honking, toot',
                           'Velcro, hook and loop fastener',
                           'Video game sound',
                           'Wail, moan',
                           'Walk, footsteps',
                           'Washing machine',
                           'Water',
                           'Water tap, faucet',
                           'Waterfall',
                           'Waves, surf',
                           'Whack, thwack',
                           'Whale vocalization',
                           'Wheeze',
                           'Whimper',
                           'Whimper (dog)',
                           'Whip',
                           'Whir',
                           'Whispering',
                           'Whistle',
                           'Whistling',
                           'White noise, pink noise',
                           'Whoop',
                           'Whoosh, swoosh, swish',
                           'Wild animals',
                           'Wildfire',
                           'Wind',
                           'Wind chime',
                           'Wind noise (microphone)',
                           'Windscreen wiper, windshield wiper',
                           'Wobble',
                           'Wolf-whistling',
                           'Wood',
                           'Writing',
                           'Yak',
                           'Yawn',
                           'Yell',
                           'Yip',
                           'Yodeling',
                           'Zing',
                           'Zipper (clothing)']

cols_to_remove = [
    'Alert', 'Audio logo', 'Bathroom sounds', 'Bicycle, tricycle',
    'Blender, food processor', 'Booing', 'Brief tone',
    'Canidae, wild dogs, wolves', 'Carbon monoxide detector, CO detector',
    'Cart', 'Chain', 'Channel, environment and background', 'Clunk',
    'Crockery breaking and smashing', 'Deformable shell', 'Digestive',
    'Dong, bong', 'Donkey, ass', 'Duck call (hunting tool)',
    'Ducks, geese, waterfowl', 'Electric rotor drone, quadcopter',
    'Error signal', 'Fizz', 'Grind', 'Gull, seagull',
    'Gurgling, bubbling', 'Human group actions', 'Human locomotion',
    'Kettle whistle', 'Keypress tone', 'Kitchen and dining room sounds',
    'Knife', 'Lock', 'Mechanical bell', 'Microphone', 'Other sourceless',
    'Pant (dog)', 'Paper rustling',
    'Power saw, circular saw, table saw', 'Puff', 'Refrigerator',
    'Respiratory sounds', 'Ringing tone, ringback tone', 'Screech',
    'Shower', 'Slurp, drinking straw', 'Snap', 'Sonic boom',
    'Sound reproduction', 'Stairs', 'Stomp, stamp', 'Stream, river',
    'Sweeping', 'Tap dance', 'Tape hiss', 'Tire squeal, skidding',
    'Unknown sound', 'Vehicle horn, car horn, honking, toot',
    'Video game sound', 'Washing machine',
    'White noise, pink noise', 'Wildfire',
    'Windscreen wiper, windshield wiper', 'Wobble',
    'Wolf-whistling', 'Yak', 'Zing'
]
indices=[]
new_list=[]
for c in as_danger_classes_original:
    if c not in cols_to_remove:
        new_list.append(c)
        indices.append(as_danger_classes_original.index(c))

print(new_list)
print(indices)
